### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Pandaqi** [Pandaqi/In-the-Same-Boat#27]
Alright, here's a list of everything that needs to be done before the next version.

# Misc bugs

- [x] Cartographer map doesn't work anymore when using the MOUSE. It does work on TOUCH (which is most important.)

- [x] Ships can start on an island tile. Then, their route just crosses an island (and monsters are happy to follow). This shouldn't happen.

- [x] More ways for fog to grow (now it might get stuck):
  - When someone trades with a dock for the first time, reveal the dock. From that moment, show dock deals (and update them)
  - Whenever someone fires, the current tile becomes discovered. Whenever someone is attacked by a monster, the current tiles becomes discovered. (With a random chance, random new tile(s) are discovered => NO DON'T DO THIS; fog becomes fragmented.)

# Role Interfaces

- [ ] Make sure everything is visible (+clickable) without scrolling. The upgrade button, and upgrade effects, can easily be obscured by a bigger interface above it. (Especially on Apple devices.)

## Captain

- [x] Switch from "gun powder" to the "treasure" resource
- [x] Add support for the "explore/ask around" action, and the messages it will return
- [x] If we actually found a treasure, display a very cheerful message, and add it to our treasure list

## Cartographer

- [ ] On server, keep track of more unit properties: speed, orientation, loot, attack/defense
- [ ] If cartographer is high enough level, send these properties for each unit
- [ ] Then, display these properties next to the unit
- [ ] VISUALLY: The cartographer map could be nicer. Shadows underneath units, for example.

# Day/Night Cycle

- [ ] Make the change GRADUALLY. (Become darker and darker, stay night, become lighter and lighter.)
- [ ] If a dock or city has been discovered, display lights: both on the sprite itself and a cut-out in the dark overlay.
- [ ] Give ships, if not in fog, nice lights as well
- [ ] Make lights flicker, especially from the lighthouses near the docks
- [ ] Also make the cartographer map darker during the night.
- [ ] (_Optional_) Implement the "lights out" feature.

# Backstory generation

Boy, this needs a lot of work.

- [x] Write script that steps along a timeline
- [x] Write list of basic events.
- [x] Pick random events, then pick follow-up events, until there's nothing left.
- [ ] When everything we need has been generated, stop the algorithm.

## Worldbuilding

During the algorithm, everything we generate (like a dock or city) is immediately placed into the world.

This means:

- [ ] Docks + trade routes
- [ ] Cities (on the coast)
- [ ] The X monster types have been discovered.
- [ ] Every group gets AI ships (based on army size and which areas they control)
- [ ] Enough treasures (including sunken ships and other landmarks)
- [ ] ??

## Distributing hints

- [x] For each treasure, generate a set of X hints
- [x] Place these hints randomly across the map
- [x] When a player is near a coast city/dock, he can choose the action "ask around"
- [x] When a player is simply on the water, he can choose the action "explore"
- [x] Doing so, returns the message(s) saved at this location.

About messages:

- [x] Each message has a message TYPE/TEMPLATE, and then parameters.
- [x] Most parameters will be known (the name of a pirate, the year a ship sank, etc.). If they refer to a dock/island that has already been discovered, it uses the name the player entered. If they referer to something that hasn't been discovered yet, it just says "a dock" or "some island".

About special types of hints:

- [ ] When a city has no information on a particular treasure, it has a certain chance of "pointing you in the right direction". It says something like "the people at city BLABLA should know more", or "all I know is that this pirate's ship sank at location BLABLA". 
  - Some of this can be done afterwards. Whenever a new hint is saved, the treasure keeps track of WHERE it is saved. Subsequently, this can be used by other treasures to point in the right direction
  - But some must be done beforehand. For example, placing an important clue inside a shipwreck at the bottom of the ocean, must be done at the start. There's no chance that a player will explore that tile soon enough for there to be pointers.

# Ships 

## Player Ships

- [ ] Create an extra (coloured) glow around/below player ships
- [ ] Create a text bubble above player ships, containing the avatars of the players inside those ships

## AI Ships

- [ ] Make AI ships from a certain group, the same as the player (ship) that plays this group
- [ ] AI ships follow trading routes, established during the backstory.
- [ ] If they encounter an unfriendly faction, they will attack.

# Reputation system

All players start with a certain reputation, based on the generated backstory.

- [ ] Attacking others will decrease your relationships. 
- [ ] Decreased relationships means you're attacked more often and are not allowed at certain places (mostly docks)
- [ ] Increased relationships means better deals at certain docks (and military support)

# Game Over

- [ ] Once a player has three treasures, the game immediately ends.
- [ ] For now, just jump to game over, display complete map and who won, and erase the game.

# Monitor

The monitor really needs to look much better.

- [ ] Make timer bigger and more readable
- [ ] Display and update dock deals, once a dock is discovered
- [x] Bring sprites to top _within sprite group_. The other stuff, like text and timer on top of the map, should always stay on top.
- [ ] In a list on the side: display in-game ships, their flag+drawing, their players.
- [ ] Create some nice graphics around it. (Some old, wooden, piraty-looking ornaments.)
- [ ] Really, the map could look more like a pirate's map, and less like a basic drawing.

# Resources

- [x] Go through all costs (upgrades and actions) and see if we can balance them. We really need more income from sea battles.
