### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Pandaqi** [Pandaqi/In-the-Same-Boat#8]
This page contains the to-do list for this project, in order.

# Preparation

- [x] Write algorithm for distributing boats (based on player count)
- [x] Write algorithm for determining roles per player (including restrictions, such as "cartographer and first mate can't be the same person")
- [x] Place docks on the world map
- [x] Create role interfaces
  - [x] Captain
  - [x] First Mate
  - [x] Cartographer
  - [x] Sailor
  - [x] Weapon Specialist

# Game structure

- [x] Copy from "Trampolinedraak"; remove everything I don't need
- [x] Create lobby => preparation => game => game over structure
- [x] Skip "preparation" for now => Allow server to create a full-blown game and send it to monitor/controllers
- [x] Create the main game timer (make turns work)
- [x] Create move to game over (use random condition for now, like turns==10)

# Visuals

- [x] Create icons for the resources
- [x] Create icons for the roles
- [x] Make the map look nicer (create graphics for docks, resource spots, etc.)

# Actual game play

- [x] Finish interfaces for all roles (including full functionality)
- [x] Display map (and other info) on monitors
- [x] Make game timer work in all cases (and continue the game properly)
